### ISSUE TITLE
Trouble getting tmux session up

### ISSUE THREAD

**Issue by awolfson** [ajkavanagh/vagrant-base-image#1]
Hi Alex, thank you for helping me with this.

My goal is to spin up a VM such that when I `vagrant ssh` into it, my tmux session is already running. Ideally I'd want it to be attached already, but if not, I can deal with that.

Maybe I'm misunderstanding what your tmux-session script accomplishes, or I'm misunderstanding what is possible in Vagrant provisioning (or both). I was really excited when I found that you had done what I was trying (and failing) to do, so hopefully not!

Anyway, no matter what I try, even when I run my tmux script successfully as part of my VM provisioning process, there are no tmux sessions running when I SSH into the box. It seems like what's happening is that tmux only runs in the temporary shell that is created to run the provision script in, rather than the shell on the VM itself.

Here is my Vagrantfile:

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

is_windows = (RbConfig::CONFIG['host_os'] =~ /mswin|mingw|cygwin/)

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "forwarded_port", guest: 4004, host: 4004
  config.vm.network "forwarded_port", guest: 587, host: 587
  config.vm.network "forwarded_port", guest: 5201, host: 5201

  config.vm.network "private_network", ip: "10.0.0.10"

  config.ssh.forward_agent = true

  config.vm.synced_folder "/share/MP4_EXPORT/", "/home/vagrant/video_hot_folder"
  config.vm.synced_folder "/share/DOWNLOAD/", "/home/vagrant/download_hot_folder"
  config.vm.synced_folder "/share/", "/home/vagrant/host_share"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
  end

  # Due to a problem with SSH forwarding on Windows machines,
  # the following config is needed.
  if is_windows
    config.vm.provision :shell, run: "always" do |shell|
     shell.inline = "touch $1 && chmod 0440 $1 && echo $2 > $1"
     shell.args = %q{/etc/sudoers.d/root_ssh_agent "Defaults    env_keep += \"SSH_AUTH_SOCK\""}
    end
  end

  config.vm.provision "shell", path: "provision.sh", run: "always"

end
```

And provision script:

```
BASHRC='/home/vagrant/.bashrc'

# Add /home/vagrant/bin directory and add to path
BIN_PATH_LINE="export PATH=\$HOME/bin:\$PATH"
FOUND=$(grep "$BIN_PATH_LINE" $BASHRC)
if [ "xxx${FOUND}" == "xxx" ]; then
  echo "$BIN_PATH_LINE" >> $BASHRC
fi

if [ -z "$TMUX"]; then
  echo 'found tmux?'

  # make the SSH_AUTH_SOCK point to a local symlink
  if [ ! -z "SSH_AUTH_SOCK" ]; then
    ln -sf "$SSH_AUTH_SOCK" "$HOME/.wrap_auth_sock"
  fi
  export SSH_AUTH_SOCK="$HOME/.wrap_auth_sock"

  PID=$(echo -n $(pidof tmux))
  if [ -z "$PID"]; then
    tmux new-session -d -P -s flug
    SRC="/home/vagrant"
    FLUG_DIR="cd $SRC/flug"
    REDIS_DIR="cd $SRC/redis/redis-3.0.7/src"
    SERVER="$FLUG_DIR && rake server:prod"
    REDIS="$REDIS_DIR && ./redis-server"
    SIDEKIQ="$FLUG_DIR && bundle exec sidekiq"
    APP="$FLUG_DIR && rake process_videos"

    tmux new-window -P -t flug:1 -n 'rails'
    tmux send-keys -t flug:1 "$SERVER" C-m
    tmux new-window -P -t flug:2 -n 'redis'
    tmux send-keys -t flug:2 "$REDIS" C-m
    tmux new-window -P -t flug:3 -n 'workers'
    tmux send-keys -t flug:3 "$SIDEKIQ" C-m
    tmux new-window -P -t flug:4 -n 'app'
    tmux send-keys -t flug:4 "$APP" C-m

    tmux select-window -t flug:1
  fi

  tmux -2 attach-session -t flug
fi
```

The script runs just fine with no errors, it just doesn't load up tmux in the VM itself.

**Comment by ajkavanagh** [comment]
Hmm, yes, that's not going to work.

To get the tmux-session script to run when you login to the vagrant box, using `vagrant ssh`, you're going to need to tag `exec tmux-session` to the end of the .profile in the vagrant user's directory.

I'd go for something like this at the end of the original  `provision.sh` file:

``` bash
START_TMUX="exec $HOME/bin/tmux-session"
PROFILE="$HOME/.profile"
FOUND=$(grep "$START_TMUX" $PROFILE)
if [ "xxx${FOUND}" == "xxx" ]; then
  echo "$START_TMUX" >> $PROFILE
fi
```

Obviously, you'll want to customise the tmux-session file to have sidekiq and reddis as above.  Note that tmux-session only needs to run on login.

This will add a line to the end of the `$HOME/.profile` file that will automatically run tmux-session when you log in.  Note I haven't tested the above, so you may have to fiddle with it.  If you have a look at the .profile file, you'll see:

```
# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.
```

An alternative is to run tmux-session as the user at the end of the provision script as the vagrant user using something like: `sudo -u vagrant /home/vagrant/bin/tmux-session`  but NOT do the `tmux -2 attach-session -t flug` at the end of it, and instead do _that_ in the `~/.profile`.  However, you'd then want to include some logic in the .profile to test whether the session is running and if not start it.  So I think only go with this approach if you want the tmux-session running _before_ you ever log in.

Hope this helps.

**Comment by awolfson** [comment]
This is _very_ helpful, thank you!

I did end up getting it to work by passing it as a command to ssh: `vagrant ssh -c "path/to/tmux-session && tmux a"`.

So that at least suffices for now, but I think eventually I'd rather have it running before log in. 

Are you sure that switching to the vagrant user would suffice to get tmux running in the _login_ shell, as opposed to just the temporary provision shell? That's what was causing me problems before.

**Comment by ajkavanagh** [comment]
If you actually launch tmux as the user, then it will stay running once the provision is over, as it should detach from the user and therefore not stop when the provision script closes its shell.

I think the main issue is going to be: if tmux is quit after you've provisioned, you'll still need a way to start it.

Thus, if you **really** need things to be running before login, then I would seriously consider adding them instead to `/etc/rc.local` such that they run on boot or creating an upstart (as this is trusty) script for them, and having them as a service.  My approach was really a 'quick and dirty mechanism that was always under manual control'.  It's a development box, rather than a production box, for interactive use.

**Comment by awolfson** [comment]
Makes sense. I did end up working on an upstart script, and I got it to
work properly (as verified in `/var/log`), but I still didn't have access
to the tmux session once the machine was booted. Could there be user issues
there, too?

Are there any real disadvantages to using `/etc/rc.local` over upstart? I
have seen many people recommending both solutions, but no real discussion
of the context in which each is appropriate. After all, if I'm only just
kicking off a script, do I really need to have it available as a service? I
just need something at boot to say, "hey, run this script please."

**Comment by ajkavanagh** [comment]
Hmm.  I'd check the user id of the running tmux process.  There's no particular disadvantage or using /etc/rc.local unless you wanted to control the tmux session using 'service.

However, you're really pushing beyond the intention of what I hacked together tmux-session for: to help a developer have a reasonable consistent dev environment that s/he can start/run various processes in different windows and panes.

You're pushing towards a semi-production type system, which either means sysv / upstart scripts or using something like supervisord to run and maintain processes/apps on a box.  I don't think this tmux-session type system is for that, nor good at it.

**Comment by awolfson** [comment]
Thanks Alex, I totally agree with that. Supervisord looks nice for what we will eventually be doing with this, and for now I think we've got to a decent place. I appreciate your help even though I took this into a completely different context!

**Comment by ajkavanagh** [comment]
Good stuff.  And good luck, I hope you find a suitable solution.  I've used supervisord in production to great effect.  I'm going to close this now, but feel free to ask any further questions.
